version: '3.8'

services:
  ros-node:
    image: "air-twizy-car:latest"
    container_name: air_container
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true  
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: "${XAUTHORITY}"
      GPU: "${GPU}"
      LIDAR: "${LIDAR}"
      INTERFACE: "${INTERFACE}"
      CAN_PORT: "${CAN_PORT}"
      NVIDIA_RUNTIME: "${NVIDIA_RUNTIME}"
      USERNAME: "${USERNAME}"
    volumes:
      - ${HOST_FOLDER_PATH}:${CONTAINER_FOLDER_PATH}:rw #(ONLY FOR DEVELOPMENT)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/tmp/.docker.xauth:rw
      - ${SHARED_FOLDER}:/home/${USERNAME}/shared_folder:rw
    runtime: "${NVIDIA_RUNTIME}"
    entrypoint: /home/air/entrypoint.sh
    command: >
      /bin/bash -c "
        if [ \"${INTERFACE}\" = \"true\" ]; then
          ros2 launch sd_vehicle_interface sd_vehicle_interface.launch.xml sd_vehicle:=twizy sd_gps_imu:=peak sd_speed_source:=vehicle_can_speed &
        fi
        if [ \"${LIDAR}\" = \"true\" ]; then
          ros2 launch velodyne velodyne-all-nodes-VLP16-launch.py
        fi
        tail -f /dev/null"
