version: '3.8'

services:
  ros-node:
    image: "air-twizy-car-image:v1"
    container_name: air_car_container
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true  
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: "${XAUTHORITY}"
      GPU: "${GPU}"
      LIDAR: "${LIDAR}"
      INTERFACE: "${INTERFACE}"
      CAN_PORT: "${CAN_PORT}"
      NVIDIA_RUNTIME: "${NVIDIA_RUNTIME}"
    volumes:
      - ${HOST_FOLDER_PATH}:${CONTAINER_FOLDER_PATH}:rw #(ONLY FOR DEVELOPMENT)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/tmp/.docker.xauth:rw
      - ${SHARED_FOLDER}:/root/shared_folder:rw
      - ${UTILS_PATH}:/root/utils:rw
    runtime: "${NVIDIA_RUNTIME}"
    entrypoint: /root/entrypoint.sh
    restart: "unless-stopped"
    command: >
      bash 
        
